from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
ACTIVITY = ROOT / "app/src/main/java/com/dhanpulse/cryptofxnative/MainActivity.java"
GRADLE = ROOT / "app/build.gradle.kts"
INDEX = ROOT / "app/src/main/assets/index.html"
MANIFEST = ROOT / "app/src/main/AndroidManifest.xml"

# Fix launcher icon and round icon using the DhanPulse asset generated by the workflow.
m = MANIFEST.read_text(encoding="utf-8")
m = re.sub(r'\n\s*android:icon="[^"]+"', '', m)
m = re.sub(r'\n\s*android:roundIcon="[^"]+"', '', m)
needle = '<application\n        android:allowBackup="true"'
replacement = ('<application\n        android:allowBackup="true"\n'
               '        android:icon="@drawable/dhanpulse_logo"\n'
               '        android:roundIcon="@drawable/dhanpulse_logo"')
if needle not in m:
    raise SystemExit("Manifest application block not found")
m = m.replace(needle, replacement, 1)
MANIFEST.write_text(m, encoding="utf-8")

# Replace the old blue DP block inside the app with the real DhanPulse logo.
h = INDEX.read_text(encoding="utf-8")
h = re.sub(r'<div class="logo">DP</div>', '<img class="logo" src="dhanpulse_logo.jpg" alt="DhanPulse">', h, count=1)
h = h.replace(
    '.logo{width:44px;height:44px;border-radius:13px;background:linear-gradient(135deg,#176bcc,#36c5d8);display:grid;place-items:center;font-weight:900;color:#04111c}',
    '.logo{width:58px;height:58px;border-radius:14px;object-fit:contain;background:#fff;padding:3px;display:block}'
)
# Remove the temporary duplicate logo that V2.1.2 inserted above the app body.
h = re.sub(r'<div id="dhanpulseBrandLogo".*?</div>', '', h, count=1, flags=re.S)
h = h.replace('Version 2.1.2 Active Signal', 'Version 2.1.3 Icon Fix')
h = h.replace('V2.1.2 Signals', 'V2.1.3 Signals')
h = h.replace('No V2.1.2 signals recorded yet.', 'No V2.1.3 signals recorded yet.')
h = h.replace('NATIVE V2.1.2', 'NATIVE V2.1.3')
INDEX.write_text(h, encoding="utf-8")

# Force WebView to drop stale UI resources after upgrading.
a = ACTIVITY.read_text(encoding="utf-8")
if 'webView.clearCache(true);' not in a:
    a = a.replace('        webView = new WebView(this);\n',
                  '        webView = new WebView(this);\n        webView.clearCache(true);\n        webView.clearHistory();\n', 1)
a = a.replace('Native V2.1.2 · ', 'Native V2.1.3 · ')
ACTIVITY.write_text(a, encoding="utf-8")

# Bump Android version so the device treats this as a fresh updated build.
g = GRADLE.read_text(encoding="utf-8")
g = re.sub(r'versionCode\s*=\s*\d+', 'versionCode = 24', g)
g = re.sub(r'versionName\s*=\s*"[^"]+"', 'versionName = "2.1.3"', g)
GRADLE.write_text(g, encoding="utf-8")

print("DhanPulse V2.1.3 launcher icon, in-app logo, cache and version patch applied")
